name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Enable Flutter Web
        run: |
          cd matrical
          flutter config --enable-web

      - name: Download Dependencies
        run: |
          cd matrical
          flutter pub get

      - name: Build
        run: |
          cd matrical
          flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./matrical/build/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
