name: Build and Deploy to tuitionscheduler.github.io

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Matrical repo
        uses: actions/checkout@v4.1.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Download Dependencies
        run: |
          cd matrical
          flutter pub get

      - name: Build
        run: |
          cd matrical
          flutter build web --web-renderer canvaskit

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout tuitionscheduler.github.io repo
        uses: actions/checkout@v4.1.7
        with:
          repository: TuitionScheduler/tuitionscheduler.github.io
          path: pages
          token: ${{ steps.generate_token.outputs.token }}

      - name: Build and Copy
        run: |
          cd matrical
          cp -avr ./build/web/* pages/

      - name: Commit and push to tuitionscheduler.github.io
        run: |
          cd pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy web build from Matrical repo"
          git push --force
