name: Scrape Sections Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check if should run
        env:
          TRIGGERING_EVENT: ${{ github.event_name }}
        run: |
          if [[ "$TRIGGERING_EVENT" == "workflow_dispatch" ]]; then
            echo "Manual run detected, running..."
            exit 0
          fi

          SPRING_START="04-21"
          SPRING_END="05-07"
          FALL_START="11-21"
          FALL_END="12-07"
          WEEKLY_DAYS="3,7"

          NOW_DATE=$(date -u +%m-%d)
          NOW_DAY=$(date -u +%u)
          WEEKLY_DAYS_CHECK=",${WEEKLY_DAYS},"

          if [[ ("$NOW_DATE" < "$SPRING_START" || "$NOW_DATE" > "$SPRING_END") && \
                ("$NOW_DATE" < "$FALL_START" || "$NOW_DATE" > "$FALL_END") && \
                "$WEEKLY_DAYS_CHECK" != *",$NOW_DAY,"* ]]; then
            echo "Date does not meet run criteria, skipping..."
            exit 1
          else
            echo "Date meets criteria, running..."
            exit 0
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
        working-directory: ./data_entry

      - name: Run Auto Scraper
        working-directory: ./data_entry
        run: poetry run python src/scrapers/auto_scrape_to_firebase.py
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
