name: Scrape Sections Data

on:
  schedule:
    - cron: "0 0 * * 0,3"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python with Poetry Cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: data_entry/poetry.lock

      - name: Install Poetry
        run: pipx install poetry

      # The --no-interaction flag is good practice for CI
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
        working-directory: ./data_entry

      - name: Run Auto Scraper
        working-directory: ./data_entry
        run: poetry run python src/scrapers/auto_scrape_to_firebase.py
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
